import { StyleSheet } from '@react-pdf/renderer'

export const palette = {
  bg: '#F7F9FC',
  white: '#FFFFFF',
  blue: '#153B73',
  blueSoft: '#EAF1FB',
  ink: '#172334',
  body: '#465468',
  border: '#D7E0EC',
  panel: '#F4F7FB',
  accent: '#2F6FCE',
  red: '#D94B4B',
}

export const pdfStyles = StyleSheet.create({
  page: {
    backgroundColor: palette.bg,
    color: palette.ink,
    fontFamily: 'Helvetica',
    fontSize: 10.5,
    lineHeight: 1.5,
    paddingTop: 46,
    paddingBottom: 54,
    paddingHorizontal: 42,
  },
  coverPage: {
    backgroundColor: palette.bg,
    color: palette.ink,
    paddingTop: 42,
    paddingBottom: 42,
    paddingHorizontal: 42,
  },
  coverFrame: {
    backgroundColor: palette.white,
    border: `1 solid ${palette.border}`,
    borderRadius: 18,
    paddingVertical: 34,
    paddingHorizontal: 30,
    minHeight: 668,
  },
  coverLogoWrap: {
    alignSelf: 'center',
    width: 264,
    minHeight: 238,
    backgroundColor: palette.white,
    border: `1 solid ${palette.border}`,
    borderRadius: 24,
    paddingVertical: 18,
    paddingHorizontal: 18,
    marginTop: 8,
    marginBottom: 30,
  },
  coverBrand: {
    width: 228,
    alignSelf: 'center',
    objectFit: 'contain',
  },
  coverRule: {
    alignSelf: 'center',
    width: 72,
    height: 4,
    backgroundColor: palette.accent,
    borderRadius: 999,
    marginBottom: 18,
  },
  coverTitleWrap: {
    alignItems: 'center',
    marginBottom: 28,
  },
  coverTitle: {
    fontSize: 27,
    fontWeight: 700,
    lineHeight: 1.15,
    marginBottom: 10,
    letterSpacing: 0.4,
    textAlign: 'center',
    color: palette.blue,
  },
  coverSubtitle: {
    fontSize: 12,
    color: '#607089',
    maxWidth: 360,
    textAlign: 'center',
  },
  coverSummaryBox: {
    backgroundColor: palette.panel,
    border: `1 solid ${palette.border}`,
    borderRadius: 14,
    padding: 20,
    marginBottom: 18,
  },
  coverSummaryText: {
    fontSize: 11,
    color: palette.body,
    marginBottom: 10,
  },
  coverField: {
    fontSize: 11,
    marginBottom: 8,
    color: palette.ink,
  },
  coverFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
  },
  coverTagline: {
    fontSize: 10,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    color: '#6E809A',
  },
  coverMarkWrap: {
    width: 76,
    height: 58,
    backgroundColor: palette.white,
    border: `1 solid ${palette.border}`,
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  coverMark: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 12,
    borderBottom: `1 solid ${palette.border}`,
  },
  headerBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerMarkWrap: {
    width: 38,
    height: 30,
    backgroundColor: palette.white,
    border: `1 solid ${palette.border}`,
    borderRadius: 10,
    paddingVertical: 5,
    paddingHorizontal: 6,
  },
  headerMark: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
  headerTitleWrap: {
    flexDirection: 'column',
  },
  headerCompany: {
    fontSize: 8.5,
    color: palette.blue,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    fontWeight: 700,
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: palette.ink,
  },
  headerMeta: {
    fontSize: 8,
    color: '#607089',
    letterSpacing: 0.3,
  },
  sectionCard: {
    backgroundColor: palette.white,
    border: `1 solid ${palette.border}`,
    borderRadius: 14,
    paddingTop: 16,
    paddingBottom: 15,
    paddingHorizontal: 18,
    marginBottom: 14,
  },
  section: {
    marginBottom: 0,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 11,
  },
  sectionNumber: {
    width: 30,
    height: 30,
    paddingTop: 7,
    marginRight: 12,
    textAlign: 'center',
    backgroundColor: palette.blueSoft,
    color: palette.blue,
    fontSize: 8.6,
    fontWeight: 700,
    borderRadius: 15,
  },
  sectionTitle: {
    flex: 1,
    fontSize: 13.2,
    lineHeight: 1.25,
    fontWeight: 700,
    color: palette.ink,
  },
  paragraph: {
    color: '#273446',
    marginBottom: 8,
  },
  bullets: {
    marginBottom: 8,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 5,
    paddingRight: 8,
  },
  bulletDot: {
    width: 12,
    color: palette.accent,
    fontSize: 11,
  },
  bulletText: {
    flex: 1,
    color: '#273446',
  },
  highlightBox: {
    backgroundColor: palette.blueSoft,
    border: `1 solid ${palette.border}`,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  highlightText: {
    fontSize: 11.5,
    color: palette.ink,
    fontWeight: 700,
  },
  secondaryText: {
    fontSize: 10,
    color: '#4E5C71',
    marginTop: 4,
  },
  note: {
    marginTop: 2,
    paddingLeft: 10,
    borderLeft: `2 solid ${palette.accent}`,
    color: '#273446',
  },
  calloutCard: {
    backgroundColor: palette.panel,
    borderRadius: 10,
    border: `1 solid ${palette.border}`,
    padding: 12,
    marginTop: 8,
  },
  calloutTitle: {
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: palette.blue,
    marginBottom: 6,
  },
  signatureIntro: {
    fontSize: 10.5,
    color: '#273446',
    marginBottom: 14,
  },
  signatureGrid: {
    flexDirection: 'row',
    gap: 14,
  },
  signatureCard: {
    flex: 1,
    border: `1 solid ${palette.border}`,
    borderRadius: 12,
    padding: 16,
    backgroundColor: palette.white,
  },
  signatureLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: palette.ink,
    marginBottom: 12,
  },
  signatureLine: {
    marginBottom: 10,
    color: '#273446',
  },
  signatureBlock: {
    backgroundColor: palette.white,
    border: `1 solid ${palette.border}`,
    borderRadius: 14,
    paddingTop: 16,
    paddingBottom: 18,
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  footer: {
    position: 'absolute',
    left: 42,
    right: 42,
    bottom: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTop: `1 solid ${palette.border}`,
    paddingTop: 8,
    fontSize: 8,
    color: '#77839A',
  },
})
